# Generated by Django 4.2.1 on 2023-06-08 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUNR', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesorr',
            new_name='Profesor',
        ),
    ]
